# Generated by Django 6.0.4 on 2026-06-27 13:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('type', models.CharField(choices=[('food', 'Food & Restaurant'), ('grocery', 'Grocery'), ('pharmacy', 'Pharmacy'), ('flowers', 'Flowers'), ('express', 'Express Delivery')], default='food', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='merchants/logos/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='merchants/covers/')),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('active', 'Active'), ('suspended', 'Suspended'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_merchants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'merchants_merchant',
            },
        ),
        migrations.CreateModel(
            name='MerchantBranch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address_text', models.CharField(max_length=300)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('service_radius_km', models.DecimalField(decimal_places=2, default=3.0, max_digits=5)),
                ('prep_time_min', models.PositiveSmallIntegerField(default=20, help_text='Average preparation time in minutes')),
                ('is_open', models.BooleanField(default=False)),
                ('accepting_orders', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='merchants.merchant')),
            ],
            options={
                'db_table': 'merchants_branch',
            },
        ),
        migrations.CreateModel(
            name='BranchWorkingHour',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False, help_text='Closed all day on this weekday')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='merchants.merchantbranch')),
            ],
            options={
                'db_table': 'merchants_branch_working_hour',
            },
        ),
        migrations.CreateModel(
            name='MerchantStaffProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profiles', to='merchants.merchantbranch')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profiles', to='merchants.merchant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'merchants_merchant_staff_profile',
            },
        ),
        migrations.AddIndex(
            model_name='merchant',
            index=models.Index(fields=['slug'], name='merchants_m_slug_edd591_idx'),
        ),
        migrations.AddIndex(
            model_name='merchant',
            index=models.Index(fields=['type', 'status'], name='merchants_m_type_ba56a3_idx'),
        ),
        migrations.AddIndex(
            model_name='merchantbranch',
            index=models.Index(fields=['merchant', 'is_open', 'accepting_orders'], name='merchants_b_merchan_0589b9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='branchworkinghour',
            unique_together={('branch', 'weekday')},
        ),
    ]
