# Generated by Django 6.0.4 on 2026-07-11 19:52

import apps.merchants.utils.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_merchanttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=apps.merchants.utils.util.merchant_cover_upload_path),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.merchants.utils.util.merchant_logo_upload_path),
        ),
    ]
