# Generated by Django 6.0.4 on 2026-06-27 12:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('offered', 'Taklif qilindi'), ('accepted', 'Qabul qilindi'), ('rejected', 'Rad etildi'), ('timed_out', 'Vaqt tugadi'), ('cancelled', 'Bekor qilindi'), ('completed', 'Bajarildi')], default='offered', max_length=20)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('offer_expires_at', models.DateTimeField()),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_assignments', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='orders.order')),
            ],
            options={
                'db_table': 'courier_assignment',
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['order', 'status'], name='courier_ass_order_i_5e6286_idx'), models.Index(fields=['courier', 'status'], name='courier_ass_courier_93f0e8_idx'), models.Index(fields=['offer_expires_at'], name='courier_ass_offer_e_1352be_idx')],
            },
        ),
    ]
