# Generated by Django 6.0.4 on 2026-06-27 12:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '__first__'),
        ('merchants', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Faol'), ('ordered', 'Buyurtma berilgan'), ('expired', "Muddati o'tgan"), ('cleared', 'Tozalangan')], default='active', max_length=20)),
                ('coupon_code', models.CharField(blank=True, max_length=50)),
                ('subtotal', models.PositiveIntegerField(default=0)),
                ('discount_amount', models.PositiveIntegerField(default=0)),
                ('delivery_fee', models.PositiveIntegerField(default=0)),
                ('service_fee', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='merchants.merchantbranch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'carts_cart',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty', models.PositiveSmallIntegerField(default=1)),
                ('unit_price', models.PositiveIntegerField(help_text='Price at time of adding to cart, in tiyin')),
                ('line_total', models.PositiveIntegerField()),
                ('snapshot_name', models.CharField(blank=True, help_text='Product name snapshot', max_length=200)),
                ('instructions', models.TextField(blank=True, help_text='Special instructions from customer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='carts.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.productvariant')),
            ],
            options={
                'db_table': 'carts_cart_item',
            },
        ),
        migrations.CreateModel(
            name='CartItemModifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField(help_text='Price delta at time of selection, in tiyin')),
                ('qty', models.PositiveSmallIntegerField(default=1)),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='carts.cartitem')),
                ('modifier_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.productmodifieroption')),
            ],
            options={
                'db_table': 'carts_cart_item_modifier',
            },
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user', 'status'], name='carts_cart_user_id_18332a_idx'),
        ),
    ]
