# Generated by Django 6.0.4 on 2026-06-27 12:47

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '__first__'),
        ('orders', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Kampaniya nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('code', models.CharField(db_index=True, help_text='Mijoz kiritadigan kod, masalan: YOZSALE20', max_length=50, unique=True, verbose_name='Promo kod')),
                ('discount_type', models.CharField(choices=[('percentage', 'Foiz (%)'), ('fixed', 'Belgilangan summa'), ('free_delivery', 'Tekin yetkazish')], default='percentage', max_length=20, verbose_name='Chegirma turi')),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Foiz yoki so'm miqdori", max_digits=12, verbose_name='Chegirma qiymati')),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Foiz chegirmalar uchun yuqori chegara', max_digits=12, null=True, verbose_name="Maksimal chegirma (so'm)")),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Minimal buyurtma summasi')),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Null = cheksiz', null=True, verbose_name='Umumiy foydalanish limiti')),
                ('per_user_limit', models.PositiveIntegerField(default=1, verbose_name='Bir foydalanuvchi uchun limit')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Hozirgi foydalanish soni')),
                ('starts_at', models.DateTimeField(verbose_name='Boshlanish vaqti')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugash vaqti')),
                ('target_type', models.CharField(choices=[('all', 'Hamma'), ('new_users', 'Yangi foydalanuvchilar'), ('specific_users', 'Tanlangan foydalanuvchilar'), ('merchant', "Muayyan do'kon")], default='all', max_length=20, verbose_name='Maqsadli auditoriya')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('active', 'Faol'), ('paused', "To'xtatilgan"), ('expired', 'Muddati tugagan'), ('exhausted', 'Limiti tugagan')], db_index=True, default='draft', max_length=20, verbose_name='Holat')),
                ('is_combinable', models.BooleanField(default=False, verbose_name='Boshqa promo bilan birlashtirish mumkinmi?')),
                ('applies_to_delivery_fee', models.BooleanField(default=False, verbose_name="Yetkazish narxiga ham qo'llansinmi?")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='allowed_promo_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Ruxsat etilgan foydalanuvchilar')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promo_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi admin')),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_campaigns', to='merchants.merchant', verbose_name="Do'kon")),
            ],
            options={
                'verbose_name': 'Promo kampaniya',
                'verbose_name_plural': 'Promo kampaniyalar',
                'db_table': 'promo_campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_amount_applied', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Qo'llanilgan chegirma (so'm)")),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Ishlatilgan vaqt')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='promo_usage', to='orders.order', verbose_name='Buyurtma')),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='promotions.promocampaign', verbose_name='Promo kampaniya')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promo_usages', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Promo foydalanish',
                'verbose_name_plural': 'Promo foydalanishlar',
                'db_table': 'promo_usages',
            },
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Referal kod')),
                ('referrer_bonus_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Referrerga bonus (so'm)")),
                ('referee_bonus_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Yangi foydalanuvchiga bonus (so'm)")),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Maksimal foydalanish soni')),
                ('use_count', models.PositiveIntegerField(default=0, verbose_name='Foydalanish soni')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_code', to=settings.AUTH_USER_MODEL, verbose_name='Egasi')),
            ],
            options={
                'verbose_name': 'Referal kod',
                'verbose_name_plural': 'Referal kodlar',
                'db_table': 'referral_codes',
            },
        ),
        migrations.CreateModel(
            name='ReferralUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referrer_bonus_credited', models.BooleanField(default=False)),
                ('referee_bonus_credited', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('first_order_placed_at', models.DateTimeField(blank=True, help_text='Bonus shu vaqtda beriladi', null=True, verbose_name='Birinchi buyurtma vaqti')),
                ('referee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='referral_usage', to=settings.AUTH_USER_MODEL, verbose_name='Yangi foydalanuvchi')),
                ('referral_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='promotions.referralcode', verbose_name='Referal kod')),
            ],
            options={
                'verbose_name': 'Referal foydalanish',
                'verbose_name_plural': 'Referal foydalanishlar',
                'db_table': 'referral_usages',
            },
        ),
        migrations.AddIndex(
            model_name='promocampaign',
            index=models.Index(fields=['code'], name='promo_campa_code_b07586_idx'),
        ),
        migrations.AddIndex(
            model_name='promocampaign',
            index=models.Index(fields=['status', 'starts_at', 'ends_at'], name='promo_campa_status_6b9c2c_idx'),
        ),
        migrations.AddIndex(
            model_name='promousage',
            index=models.Index(fields=['promo', 'user'], name='promo_usage_promo_i_c0eeb0_idx'),
        ),
        migrations.AddIndex(
            model_name='promousage',
            index=models.Index(fields=['user', 'used_at'], name='promo_usage_user_id_afe3df_idx'),
        ),
    ]
