# Generated by Django 6.0.4 on 2026-06-27 12:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(choices=[('tashkent', 'Tashkent'), ('samarkand', 'Samarkand'), ('bukhara', 'Bukhara'), ('namangan', 'Namangan'), ('andijan', 'Andijan')], default='tashkent', max_length=50)),
                ('center_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('center_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('radius_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('delivery_fee_override', models.PositiveIntegerField(blank=True, help_text='Override delivery fee in UZS smallest unit for this zone', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'locations_service_zone',
            },
        ),
        migrations.CreateModel(
            name='GeocodingCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.CharField(max_length=500, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('formatted_address', models.TextField(blank=True)),
                ('provider', models.CharField(choices=[('yandex', 'Yandex'), ('google', 'Google'), ('2gis', '2GIS')], default='yandex', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'locations_geocoding_cache',
                'indexes': [models.Index(fields=['query'], name='locations_g_query_f27035_idx')],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Home, Work, etc.', max_length=100)),
                ('address_line', models.CharField(max_length=255)),
                ('landmark', models.CharField(blank=True, help_text='Near landmark for local delivery', max_length=255)),
                ('entrance', models.CharField(blank=True, max_length=20)),
                ('floor', models.CharField(blank=True, max_length=10)),
                ('apartment', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(choices=[('tashkent', 'Tashkent'), ('samarkand', 'Samarkand'), ('bukhara', 'Bukhara'), ('namangan', 'Namangan'), ('andijan', 'Andijan')], default='tashkent', max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'locations_address',
                'indexes': [models.Index(fields=['user', 'is_default'], name='locations_a_user_id_fce2a5_idx')],
            },
        ),
    ]
