# Generated by Django 6.0.6 on 2026-07-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('qarshi', 'Qarshi')], default='qarshi', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicezone',
            name='city',
            field=models.CharField(choices=[('qarshi', 'Qarshi')], default='qarshi', max_length=50),
        ),
    ]
