# Generated by Django 6.0.4 on 2026-06-27 12:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAnalyticsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('total_users', models.PositiveIntegerField(default=0)),
                ('total_customers', models.PositiveIntegerField(default=0)),
                ('total_merchants', models.PositiveIntegerField(default=0)),
                ('total_couriers', models.PositiveIntegerField(default=0)),
                ('active_couriers', models.PositiveIntegerField(default=0)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('delivered_orders', models.PositiveIntegerField(default=0)),
                ('cancelled_orders', models.PositiveIntegerField(default=0)),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('paid_orders_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('avg_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('avg_delivery_minutes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analytics_daily_snapshot',
                'ordering': ['-date'],
            },
        ),
    ]
