# Generated by Django 6.0.4 on 2026-06-27 13:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merchant_rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name="Do'kon bahosi (1–5)")),
                ('merchant_comment', models.TextField(blank=True, verbose_name="Do'kon haqida izoh")),
                ('courier_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Kuryer bahosi (1–5)')),
                ('courier_comment', models.TextField(blank=True, verbose_name='Kuryer haqida izoh')),
                ('status', models.CharField(choices=[('pending', 'Moderatsiyada'), ('visible', "Ko'rinadigan"), ('hidden', 'Yashirilgan'), ('flagged', 'Shikoyat qilingan')], db_index=True, default='visible', max_length=20, verbose_name='Holat')),
                ('merchant_reply', models.TextField(blank=True, verbose_name="Do'kon javobi")),
                ('merchant_replied_at', models.DateTimeField(blank=True, null=True, verbose_name='Javob vaqti')),
                ('flag_count', models.PositiveSmallIntegerField(default=0, verbose_name='Shikoyat soni')),
                ('admin_note', models.TextField(blank=True, verbose_name='Admin eslatmasi')),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courier_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Kuryer')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Mijoz')),
                ('flagged_by', models.ManyToManyField(blank=True, related_name='flagged_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Shikoyat qiluvchilar')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='merchants.merchant', verbose_name="Do'kon")),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Moderator')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review', to='orders.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviewlar',
                'db_table': 'reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('offensive', "Haqoratli so'zlar"), ('irrelevant', "Buyurtmaga aloqasi yo'q"), ('fake', 'Soxta review'), ('other', 'Boshqa')], default='other', max_length=20, verbose_name='Sabab')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flagged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_flags', to=settings.AUTH_USER_MODEL, verbose_name='Shikoyat qiluvchi')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='reviews.review', verbose_name='Review')),
            ],
            options={
                'verbose_name': 'Review shikoyati',
                'verbose_name_plural': 'Review shikoyatlari',
                'db_table': 'review_flags',
            },
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='reviews/images/%Y/%m/', verbose_name='Rasm')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reviews.review', verbose_name='Review')),
            ],
            options={
                'verbose_name': 'Review rasmi',
                'verbose_name_plural': 'Review rasmlari',
                'db_table': 'review_images',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['merchant', 'status'], name='reviews_merchan_8d7087_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['courier', 'status'], name='reviews_courier_79ba75_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['customer', 'created_at'], name='reviews_custome_785a9b_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['status', 'created_at'], name='reviews_status_422c9e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewflag',
            unique_together={('review', 'flagged_by')},
        ),
    ]
