# Generated by Django 6.0.4 on 2026-06-27 13:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('push_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('promotional_push', models.BooleanField(default=True)),
                ('promotional_sms', models.BooleanField(default=False)),
                ('promotional_email', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.TextField()),
                ('provider', models.CharField(choices=[('fcm', 'Firebase Cloud Messaging'), ('apns', 'Apple Push Notification Service')], default='fcm', max_length=20)),
                ('device_id', models.CharField(blank=True, help_text='Unique device identifier (e.g. Android ID or iOS identifierForVendor)', max_length=255)),
                ('device_name', models.CharField(blank=True, max_length=255)),
                ('app_version', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_device_tokens',
                'indexes': [models.Index(fields=['user', 'is_active'], name='notificatio_user_id_93f131_idx')],
                'unique_together': {('user', 'device_id', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('order_created', 'Order Created'), ('order_merchant_confirmed', 'Merchant Confirmed'), ('order_preparing', 'Preparing'), ('order_ready_for_pickup', 'Ready for Pickup'), ('order_courier_assigned', 'Courier Assigned'), ('order_picked_up', 'Picked Up'), ('order_on_the_way', 'On the Way'), ('order_delivered', 'Delivered'), ('order_cancelled', 'Order Cancelled'), ('payment_received', 'Payment Received'), ('refund_created', 'Refund Created'), ('refund_completed', 'Refund Completed'), ('courier_new_order_offer', 'New Order Offer'), ('courier_order_offer_expired', 'Order Offer Expired'), ('merchant_new_order', 'New Order for Merchant'), ('merchant_order_timeout', 'Order Confirmation Timeout'), ('otp_sent', 'OTP Sent'), ('account_verified', 'Account Verified')], max_length=60)),
                ('channel', models.CharField(choices=[('push', 'Push Notification'), ('sms', 'SMS'), ('email', 'Email'), ('in_app', 'In-App'), ('telegram', 'Telegram (Admin)')], max_length=20)),
                ('notification_type', models.CharField(choices=[('transactional', 'Transactional'), ('promotional', 'Promotional'), ('system', 'System')], default='transactional', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict, help_text='Extra payload for deep-linking')),
                ('push_token', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('failure_reason', models.TextField(blank=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('order_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'channel', 'status'], name='notificatio_recipie_1318f1_idx'), models.Index(fields=['recipient', 'event', 'created_at'], name='notificatio_recipie_e5d9d6_idx'), models.Index(fields=['status', 'attempt_count'], name='notificatio_status_f649e5_idx'), models.Index(fields=['order_id'], name='notificatio_order_i_25eb33_idx'), models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx')],
            },
        ),
    ]
