# Generated by Django 6.0.6 on 2026-07-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.CharField(choices=[('order_created', 'Order Created'), ('order_merchant_confirmed', 'Merchant Confirmed'), ('order_preparing', 'Preparing'), ('order_ready_for_pickup', 'Ready for Pickup'), ('order_courier_assigned', 'Courier Assigned'), ('order_picked_up', 'Picked Up'), ('order_on_the_way', 'On the Way'), ('order_delivered', 'Delivered'), ('order_cancelled', 'Order Cancelled'), ('payment_received', 'Payment Received'), ('refund_created', 'Refund Created'), ('refund_completed', 'Refund Completed'), ('courier_new_order_offer', 'New Order Offer'), ('courier_order_offer_expired', 'Order Offer Expired'), ('merchant_new_order', 'New Order for Merchant'), ('merchant_order_timeout', 'Order Confirmation Timeout'), ('account_verified', 'Account Verified')], max_length=60),
        ),
    ]
